version: 2.1
executors:
  default-executor:
    docker:
      - image: cimg/node:20.17.0
jobs:
  install-dependencies:
    executor: default-executor
    steps:
      - checkout
      - run: cat package*.json > cachekey
      - restore_cache:
          keys:
            - oss-zenika-com-npm-{{ checksum "cachekey" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: oss-zenika-com-npm-{{ checksum "cachekey" }}
          paths:
            - ~/.npm
      - persist_to_workspace:
          root: .
          paths: .

  check-biome:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Check biome"
          command: npm run check

workflows:
  version: 2
  quality-checks:
    jobs:
      - install-dependencies
      # - check-biome:
      #     requires:
      #       - install-dependencies
