version: 2.1
executors:
  default-executor:
    docker:
      - image: cimg/node:20.17.0
jobs:
  install-dependencies:
    executor: default-executor
    steps:
      - checkout
      - run: cat package*.json > cachekey
      - restore_cache:
          keys:
            - oss-zenika-com-npm-{{ checksum "cachekey" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: oss-zenika-com-npm-{{ checksum "cachekey" }}
          paths:
            - ~/.npm
      - persist_to_workspace:
          root: .
          paths: .

  check-prettier:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Check prettier"
          command: npm run format:check

  check-linter:
    executor: default-executor
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Check linter"
          command: echo 'Fake linter check'

workflows:
  version: 2
  quality-checks:
    jobs:
      - install-dependencies
      - check-prettier:
          requires:
            - install-dependencies
      - check-linter:
          requires:
            - install-dependencies
